INSERT INTO `html_content` (lang, page, code, type, content) VALUES
('ru', 'CABINET', 'PAGE_TITLE', 'STRING', 'LOVA - cabinet'),
('ru', 'CABINET', 'PAGE_DESCRIPTION', 'STRING', 'Я зарегистрирован на lova.su. Там вся страна!'),
('ru', 'CABINET', 'SHARE_HINT_FACEBOOK', 'STRING', 'Поделиться в Facebook'),
('ru', 'CABINET', 'SHARE_HINT_VK', 'STRING', 'Поделиться В Контакте'),
('ru', 'CABINET', 'SHARE_HINT_MY_MAIL', 'STRING', 'Поделиться в Моем Мире @Mail.ru'),
('ru', 'CABINET', 'PROFILE', 'STRING', 'Профиль'),
('ru', 'CABINET', 'LOGOUT', 'STRING', 'Выйти'),
('ru', 'CABINET', 'REF_LINK_LABEL', 'STRING', 'Ваша ссылка для приглашения'), 
('ru', 'CABINET', 'ALERT_LIKE', 'HTML', '<strong>ВНИМАНИЕ:</strong> Чтобы использовать все возможности кабинета, поставьте, пожалуйста, лайк!'),
('ru', 'CABINET', 'COUNTDOWN_HEADER', 'STRING', 'Установленный минимум регистраций до старта:'),
('ru', 'CABINET', 'COUNTDOWN_FOOTER', 'STRING', 'Ускорь старт проекта, <a href="#inviteDiv" data-toggle="modal">пригласи друзей</a>!'),
('ru', 'CABINET', 'ALERT_EMAIL', 'HTML', 'Для подтверждения e-mail перейдите по ссылке в письме, полученном при регистрации.<br>Если вы не получили письмо, проверьте папку Спам, нажмите <a href="#" onclick="sendFirstEmail();return false;">здесь</a> для повторной отправки.<br>Если письмо по прежнему не приходит к вам, значит вы используете почтовый ящик: mail.ru, bk.ru, list.ru, inbox.ru, liva.it.<br>Пройдите в профиль и замените свой почтовый адрес (mail.ru, bk.ru, list.ru, inbox.ru, liva.it) на любой другой, который у вас есть.'),
('ru', 'CABINET', 'ACCOUNT_HEADER', 'HTML', '<i>Прогнозируемый нами, Ваш доход в работающем проекте:<i>'),
('ru', 'CABINET', 'ACCOUNT_REGISTERED', 'STRING', 'Зарегистрировано'),
('ru', 'CABINET', 'ACCOUNT_FOND', 'STRING', 'За участие в фонде'),
('ru', 'CABINET', 'ACCOUNT_REFERALS', 'STRING', 'За привлечение'),
('ru', 'CABINET', 'ACCOUNT_REFERALS_INVITED', 'STRING', 'Вы пригласили'),
('ru', 'CABINET', 'INVITE_LABEL', 'STRING', 'Пригласи друга'),
('ru', 'CABINET', 'INVITE_ALERT_PROFILE', 'STRING', 'Для того, что бы отправлять приглашения, в вашем профиле должно быть заполнено поле "Фамилия"'),
('ru', 'CABINET', 'INVITE_ALERT_FIELDS_REQUIRED', 'STRING', 'Имя и e-mail обязательны'),
('ru', 'CABINET', 'INVITE_ALERT_SEND', 'STRING', 'Приглашение отправлено, Вы можете пригласить ещё одного друга!'),
('ru', 'CABINET', 'INVITE_FRIEND_NAME', 'STRING', 'Введите имя друга'),
('ru', 'CABINET', 'INVITE_FRIEND_EMAIL', 'STRING', 'и его e-mail'),
('ru', 'CABINET', 'INVITE_BUTTON_CLOSE', 'STRING', 'Закрыть'),
('ru', 'CABINET', 'INVITE_BUTTON_SEND', 'STRING', 'Пригласить'),
('ru', 'CABINET', 'EMAIL_WARN_LABEL', 'STRING', 'ВНИМАНИЕ!!!'),
('ru', 'CABINET', 'EMAIL_WARN_BODY', 'HTML', '<p>Ваш аккаунт зарегистрирован на почтовый ящик, который располагается у почтовых провайдеров: mail.ru, bk.ru, list.ru, inbox.ru, liva.it<p>Пожалуйста, зайдите в свой профиль и впишите другую свою почту любого другого провайдера.<p>Аккаунты, оставшиеся на почтовых ящиках, что находятся на mail.ru, bk.ru, list.ru, inbox.ru, liva.it, не смогут работать в дальнейшем.'),
('ru', 'CABINET', 'EMAIL_WARN_BUTTON_CLOSE', 'STRING', 'Закрыть');

INSERT INTO `html_content` (lang, page, code, type, content) VALUES
('en', 'CABINET', 'PAGE_TITLE', 'STRING', 'LOVA - cabinet'),
('en', 'CABINET', 'PAGE_DESCRIPTION', 'STRING', 'Я зарегистрирован на lova.su. Там вся страна!'),
('en', 'CABINET', 'SHARE_HINT_FACEBOOK', 'STRING', 'Поделиться в Facebook'),
('en', 'CABINET', 'SHARE_HINT_VK', 'STRING', 'Поделиться В Контакте'),
('en', 'CABINET', 'SHARE_HINT_MY_MAIL', 'STRING', 'Поделиться в Моем Мире @Mail.ru'),
('en', 'CABINET', 'PROFILE', 'STRING', 'Профиль'),
('en', 'CABINET', 'LOGOUT', 'STRING', 'Выйти'),
('en', 'CABINET', 'REF_LINK_LABEL', 'STRING', 'Ваша ссылка для приглашения'), 
('en', 'CABINET', 'ALERT_LIKE', 'HTML', '<strong>ВНИМАНИЕ:</strong> Чтобы использовать все возможности кабинета, поставьте, пожалуйста, лайк!'),
('en', 'CABINET', 'COUNTDOWN_HEADER', 'STRING', 'Установленный минимум регистраций до старта:'),
('en', 'CABINET', 'COUNTDOWN_FOOTER', 'STRING', 'Ускорь старт проекта, <a href="#inviteDiv" data-toggle="modal">пригласи друзей</a>!'),
('en', 'CABINET', 'ALERT_EMAIL', 'HTML', 'Для подтверждения e-mail перейдите по ссылке в письме, полученном при регистрации.<br>Если вы не получили письмо, проверьте папку Спам, нажмите <a href="#" onclick="sendFirstEmail();return false;">здесь</a> для повторной отправки.<br>Если письмо по прежнему не приходит к вам, значит вы используете почтовый ящик: mail.ru, bk.ru, list.ru, inbox.ru, liva.it.<br>Пройдите в профиль и замените свой почтовый адрес (mail.ru, bk.ru, list.ru, inbox.ru, liva.it) на любой другой, который у вас есть.'),
('en', 'CABINET', 'ACCOUNT_HEADER', 'HTML', '<i>Прогнозируемый нами, Ваш доход в работающем проекте:</i>'),
('en', 'CABINET', 'ACCOUNT_REGISTERED', 'STRING', 'Зарегистрировано'),
('en', 'CABINET', 'ACCOUNT_FOND', 'STRING', 'За участие в фонде'),
('en', 'CABINET', 'ACCOUNT_REFERALS', 'STRING', 'За привлечение'),
('en', 'CABINET', 'ACCOUNT_REFERALS_INVITED', 'STRING', 'Вы пригласили'),
('en', 'CABINET', 'INVITE_LABEL', 'STRING', 'Пригласи друга'),
('en', 'CABINET', 'INVITE_ALERT_PROFILE', 'STRING', 'Для того, что бы отправлять приглашения, в вашем профиле должно быть заполнено поле "Фамилия"'),
('en', 'CABINET', 'INVITE_ALERT_FIELDS_REQUIRED', 'STRING', 'Имя и e-mail обязательны'),
('en', 'CABINET', 'INVITE_ALERT_SEND', 'STRING', 'Приглашение отправлено, Вы можете пригласить ещё одного друга!'),
('en', 'CABINET', 'INVITE_FRIEND_NAME', 'STRING', 'Введите имя друга'),
('en', 'CABINET', 'INVITE_FRIEND_EMAIL', 'STRING', 'и его e-mail'),
('en', 'CABINET', 'INVITE_BUTTON_CLOSE', 'STRING', 'Закрыть'),
('en', 'CABINET', 'INVITE_BUTTON_SEND', 'STRING', 'Пригласить'),
('en', 'CABINET', 'EMAIL_WARN_LABEL', 'STRING', 'ВНИМАНИЕ!!!'),
('en', 'CABINET', 'EMAIL_WARN_BODY', 'HTML', '<p>Ваш аккаунт зарегистрирован на почтовый ящик, который располагается у почтовых провайдеров: mail.ru, bk.ru, list.ru, inbox.ru, liva.it<p>Пожалуйста, зайдите в свой профиль и впишите другую свою почту любого другого провайдера.<p>Аккаунты, оставшиеся на почтовых ящиках, что находятся на mail.ru, bk.ru, list.ru, inbox.ru, liva.it, не смогут работать в дальнейшем.'),
('en', 'CABINET', 'EMAIL_WARN_BUTTON_CLOSE', 'STRING', 'Закрыть');

INSERT INTO `html_content` (lang, page, code, type, content) VALUES
('ua', 'CABINET', 'PAGE_TITLE', 'STRING', 'LOVA - cabinet'),
('ua', 'CABINET', 'PAGE_DESCRIPTION', 'STRING', 'Я зарегистрирован на lova.su. Там вся страна!'),
('ua', 'CABINET', 'SHARE_HINT_FACEBOOK', 'STRING', 'Поделиться в Facebook'),
('ua', 'CABINET', 'SHARE_HINT_VK', 'STRING', 'Поделиться В Контакте'),
('ua', 'CABINET', 'SHARE_HINT_MY_MAIL', 'STRING', 'Поделиться в Моем Мире @Mail.ru'),
('ua', 'CABINET', 'PROFILE', 'STRING', 'Профиль'),
('ua', 'CABINET', 'LOGOUT', 'STRING', 'Выйти'),
('ua', 'CABINET', 'REF_LINK_LABEL', 'STRING', 'Ваша ссылка для приглашения'), 
('ua', 'CABINET', 'ALERT_LIKE', 'HTML', '<strong>ВНИМАНИЕ:</strong> Чтобы использовать все возможности кабинета, поставьте, пожалуйста, лайк!'),
('ua', 'CABINET', 'COUNTDOWN_HEADER', 'STRING', 'Установленный минимум регистраций до старта:'),
('ua', 'CABINET', 'COUNTDOWN_FOOTER', 'STRING', 'Ускорь старт проекта, <a href="#inviteDiv" data-toggle="modal">пригласи друзей</a>!'),
('ua', 'CABINET', 'ALERT_EMAIL', 'HTML', 'Для подтверждения e-mail перейдите по ссылке в письме, полученном при регистрации.<br>Если вы не получили письмо, проверьте папку Спам, нажмите <a href="#" onclick="sendFirstEmail();return false;">здесь</a> для повторной отправки.<br>Если письмо по прежнему не приходит к вам, значит вы используете почтовый ящик: mail.ru, bk.ru, list.ru, inbox.ru, liva.it.<br>Пройдите в профиль и замените свой почтовый адрес (mail.ru, bk.ru, list.ru, inbox.ru, liva.it) на любой другой, который у вас есть.'),
('ua', 'CABINET', 'ACCOUNT_HEADER', 'HTML', '<i>Прогнозируемый нами, Ваш доход в работающем проекте:<i>'),
('ua', 'CABINET', 'ACCOUNT_REGISTERED', 'STRING', 'Зарегистрировано'),
('ua', 'CABINET', 'ACCOUNT_FOND', 'STRING', 'За участие в фонде'),
('ua', 'CABINET', 'ACCOUNT_REFERALS', 'STRING', 'За привлечение'),
('ua', 'CABINET', 'ACCOUNT_REFERALS_INVITED', 'STRING', 'Вы пригласили'),
('ua', 'CABINET', 'INVITE_LABEL', 'STRING', 'Пригласи друга'),
('ua', 'CABINET', 'INVITE_ALERT_PROFILE', 'STRING', 'Для того, что бы отправлять приглашения, в вашем профиле должно быть заполнено поле "Фамилия"'),
('ua', 'CABINET', 'INVITE_ALERT_FIELDS_REQUIRED', 'STRING', 'Имя и e-mail обязательны'),
('ua', 'CABINET', 'INVITE_ALERT_SEND', 'STRING', 'Приглашение отправлено, Вы можете пригласить ещё одного друга!'),
('ua', 'CABINET', 'INVITE_FRIEND_NAME', 'STRING', 'Введите имя друга'),
('ua', 'CABINET', 'INVITE_FRIEND_EMAIL', 'STRING', 'и его e-mail'),
('ua', 'CABINET', 'INVITE_BUTTON_CLOSE', 'STRING', 'Закрыть'),
('ua', 'CABINET', 'INVITE_BUTTON_SEND', 'STRING', 'Пригласить'),
('ua', 'CABINET', 'EMAIL_WARN_LABEL', 'STRING', 'ВНИМАНИЕ!!!'),
('ua', 'CABINET', 'EMAIL_WARN_BODY', 'HTML', '<p>Ваш аккаунт зарегистрирован на почтовый ящик, который располагается у почтовых провайдеров: mail.ru, bk.ru, list.ru, inbox.ru, liva.it<p>Пожалуйста, зайдите в свой профиль и впишите другую свою почту любого другого провайдера.<p>Аккаунты, оставшиеся на почтовых ящиках, что находятся на mail.ru, bk.ru, list.ru, inbox.ru, liva.it, не смогут работать в дальнейшем.'),
('ua', 'CABINET', 'EMAIL_WARN_BUTTON_CLOSE', 'STRING', 'Закрыть');
