INSERT INTO `html_content` (lang, page, code, type, content) VALUES
('ru', 'MAIN', 'PAGE_DESCRIPTION', 'STRING', 'Я зарегистрирован на lova.su. Там вся страна!'),
('ru', 'MAIN', 'PAGE_TITLE', 'STRING', 'LOVA'),
('ru', 'MAIN', 'FORGOT_PASSWORD_LINK', 'STRING', 'Забыли пароль?'),
('ru', 'MAIN', 'LOGIN_EMAIL', 'STRING', 'Введите адрес почтового ящика'),
('ru', 'MAIN', 'LOGIN_EMAIL_HINT', 'STRING', 'E-mail'),
('ru', 'MAIN', 'LOGIN_PASSWORD', 'STRING', 'и пароль'),
('ru', 'MAIN', 'LOGIN_PASSWORD_HINT', 'STRING', 'Пароль'),
('ru', 'MAIN', 'LOGIN', 'STRING', 'Войти'),
('ru', 'MAIN', 'REGISTER', 'STRING', 'Регистрация'),
('ru', 'MAIN', 'SHARE_FACEBOOK', 'STRING', 'Поделиться в Facebook'),
('ru', 'MAIN', 'SHARE_VK', 'STRING', 'Поделиться В Контакте'),
('ru', 'MAIN', 'SHARE_ODNOKLASSNIKI', 'STRING', 'Добавить в Одноклассники'),
('ru', 'MAIN', 'SHARE_MAILRU', 'STRING', 'Поделиться в Моем Мире @Mail.ru'),
('ru', 'MAIN', 'REGISTER_WINDOW_CAPTION', 'STRING', 'Регистрация'),
('ru', 'MAIN', 'REGISTER_WINDOW_FIRST_NAME', 'STRING', 'Имя'),
('ru', 'MAIN', 'REGISTER_WINDOW_LAST_NAME', 'STRING', 'Фамилия'),
('ru', 'MAIN', 'REGISTER_WINDOW_LOGIN', 'STRING', 'Ник'),
('ru', 'MAIN', 'REGISTER_WINDOW_PASSWORD', 'STRING', 'Пароль'),
('ru', 'MAIN', 'REGISTER_WINDOW_EMAIL', 'STRING', 'Почта'),
('ru', 'MAIN', 'REGISTER_WINDOW_CLOSE_BTN', 'STRING', 'Закрыть'),
('ru', 'MAIN', 'REGISTER_WINDOW_REGISTER_BTN', 'STRING', 'Регистрация'),
('ru', 'MAIN', 'RESTORE_WINDOW_CAPTION', 'STRING', 'Восстановление пароля'),
('ru', 'MAIN', 'RESTORE_WINDOW_USER_NOT_FOUND', 'STRING', 'Ник или E-mail не найден'),
('ru', 'MAIN', 'RESTORE_WINDOW_EMAIL_WAS_SENT', 'STRING', 'Сcылка для восстановления пароля отправлена на почту'),
('ru', 'MAIN', 'RESTORE_WINDOW_LOGIN', 'STRING', 'Введите ник'),
('ru', 'MAIN', 'RESTORE_WINDOW_EMAIL', 'STRING', 'Или e-mail'),
('ru', 'MAIN', 'RESTORE_WINDOW_CLOSE_BTN', 'STRING', 'Закрыть'),
('ru', 'MAIN', 'RESTORE_WINDOW_RESTORE_BTN', 'STRING', 'Восстановить'),
('ru', 'PROFILE', 'PAGE_TITLE', 'STRING', 'LOVA - cabinet'),
('ru', 'PROFILE', 'PROFILE_FIELDS', 'STRING', 'Пожалуйста, заполните обязательные поля.'),
('ru', 'PROFILE', 'PROFILE_LANG_RU', 'STRING', 'Русский'),
('ru', 'PROFILE', 'PROFILE_LANG_EN', 'STRING', 'English'),
('ru', 'PROFILE', 'PROFILE_LANG_UA', 'STRING', 'Українська'),
('ru', 'PROFILE', 'PROFILE_LANG', 'STRING', 'Язык'),
('ru', 'PROFILE', 'PROFILE_FIRST_NAME', 'STRING', 'Имя'),
('ru', 'PROFILE', 'PROFILE_LAST_NAME', 'STRING', 'Фамилия'),
('ru', 'PROFILE', 'PROFILE_LOGIN', 'STRING', 'Ник'),
('ru', 'PROFILE', 'PROFILE_EMAIL', 'STRING', 'Почта'),
('ru', 'PROFILE', 'PROFILE_PASSWORD', 'STRING', 'Пароль'),
('ru', 'PROFILE', 'PROFILE_PHONE', 'STRING', 'Телефон'),
('ru', 'PROFILE', 'PROFILE_COUNTRY', 'STRING', 'Страна'),
('ru', 'PROFILE', 'PROFILE_SKYPE', 'STRING', 'Скайп'),
('ru', 'PROFILE', 'PROFILE_REFERAL', 'STRING', 'Пригласил'),
('ru', 'PROFILE', 'PROFILE_REFERAL_HINT', 'STRING', 'поле можно изменить в течении 7 дней с момента регистрации'),
('ru', 'PROFILE', 'PROFILE_SUBSCRIBE', 'STRING', 'Получать еженедельную рассылку'),
('ru', 'PROFILE', 'PROFILE_SAVE_BTN', 'STRING', 'Сохранить'),
('ru', 'PROFILE', 'PROFILE_CLOSE_BTN', 'STRING', 'Закрыть');


INSERT INTO `html_content` (lang, page, code, type, content) VALUES
('en', 'MAIN', 'PAGE_DESCRIPTION', 'STRING', 'Я зарегистрирован на lova.su. Там вся страна!'),
('en', 'MAIN', 'PAGE_TITLE', 'STRING', 'LOVA'),
('en', 'MAIN', 'FORGOT_PASSWORD_LINK', 'STRING', 'Забыли пароль?'),
('en', 'MAIN', 'LOGIN_EMAIL', 'STRING', 'Введите адрес почтового ящика'),
('en', 'MAIN', 'LOGIN_EMAIL_HINT', 'STRING', 'E-mail'),
('en', 'MAIN', 'LOGIN_PASSWORD', 'STRING', 'и пароль'),
('en', 'MAIN', 'LOGIN_PASSWORD_HINT', 'STRING', 'Пароль'),
('en', 'MAIN', 'LOGIN', 'STRING', 'Войти'),
('en', 'MAIN', 'REGISTER', 'STRING', 'Регистрация'),
('en', 'MAIN', 'SHARE_FACEBOOK', 'STRING', 'Поделиться в Facebook'),
('en', 'MAIN', 'SHARE_VK', 'STRING', 'Поделиться В Контакте'),
('en', 'MAIN', 'SHARE_ODNOKLASSNIKI', 'STRING', 'Добавить в Одноклассники'),
('en', 'MAIN', 'SHARE_MAILRU', 'STRING', 'Поделиться в Моем Мире @Mail.ru'),
('en', 'MAIN', 'REGISTER_WINDOW_CAPTION', 'STRING', 'Регистрация'),
('en', 'MAIN', 'REGISTER_WINDOW_FIRST_NAME', 'STRING', 'Имя'),
('en', 'MAIN', 'REGISTER_WINDOW_LAST_NAME', 'STRING', 'Фамилия'),
('en', 'MAIN', 'REGISTER_WINDOW_LOGIN', 'STRING', 'Ник'),
('en', 'MAIN', 'REGISTER_WINDOW_PASSWORD', 'STRING', 'Пароль'),
('en', 'MAIN', 'REGISTER_WINDOW_EMAIL', 'STRING', 'Почта'),
('en', 'MAIN', 'REGISTER_WINDOW_CLOSE_BTN', 'STRING', 'Закрыть'),
('en', 'MAIN', 'REGISTER_WINDOW_REGISTER_BTN', 'STRING', 'Регистрация'),
('en', 'MAIN', 'RESTORE_WINDOW_CAPTION', 'STRING', 'Восстановление пароля'),
('en', 'MAIN', 'RESTORE_WINDOW_USER_NOT_FOUND', 'STRING', 'Ник или E-mail не найден'),
('en', 'MAIN', 'RESTORE_WINDOW_EMAIL_WAS_SENT', 'STRING', 'Сcылка для восстановления пароля отправлена на почту'),
('en', 'MAIN', 'RESTORE_WINDOW_LOGIN', 'STRING', 'Введите ник'),
('en', 'MAIN', 'RESTORE_WINDOW_EMAIL', 'STRING', 'Или e-mail'),
('en', 'MAIN', 'RESTORE_WINDOW_CLOSE_BTN', 'STRING', 'Закрыть'),
('en', 'MAIN', 'RESTORE_WINDOW_RESTORE_BTN', 'STRING', 'Восстановить'),
('en', 'PROFILE', 'PAGE_TITLE', 'STRING', 'LOVA - cabinet'),
('en', 'PROFILE', 'PROFILE_FIELDS', 'STRING', 'Пожалуйста, заполните обязательные поля.'),
('en', 'PROFILE', 'PROFILE_LANG_RU', 'STRING', 'Русский'),
('en', 'PROFILE', 'PROFILE_LANG_EN', 'STRING', 'English'),
('en', 'PROFILE', 'PROFILE_LANG_UA', 'STRING', 'Українська'),
('en', 'PROFILE', 'PROFILE_LANG', 'STRING', 'Язык'),
('en', 'PROFILE', 'PROFILE_FIRST_NAME', 'STRING', 'Имя'),
('en', 'PROFILE', 'PROFILE_LAST_NAME', 'STRING', 'Фамилия'),
('en', 'PROFILE', 'PROFILE_LOGIN', 'STRING', 'Ник'),
('en', 'PROFILE', 'PROFILE_EMAIL', 'STRING', 'Почта'),
('en', 'PROFILE', 'PROFILE_PASSWORD', 'STRING', 'Пароль'),
('en', 'PROFILE', 'PROFILE_PHONE', 'STRING', 'Телефон'),
('en', 'PROFILE', 'PROFILE_COUNTRY', 'STRING', 'Страна'),
('en', 'PROFILE', 'PROFILE_SKYPE', 'STRING', 'Скайп'),
('en', 'PROFILE', 'PROFILE_REFERAL', 'STRING', 'Пригласил'),
('en', 'PROFILE', 'PROFILE_REFERAL_HINT', 'STRING', 'поле можно изменить в течении 7 дней с момента регистрации'),
('en', 'PROFILE', 'PROFILE_SUBSCRIBE', 'STRING', 'Получать еженедельную рассылку'),
('en', 'PROFILE', 'PROFILE_SAVE_BTN', 'STRING', 'Сохранить'),
('en', 'PROFILE', 'PROFILE_CLOSE_BTN', 'STRING', 'Закрыть');

INSERT INTO `html_content` (lang, page, code, type, content) VALUES
('ua', 'MAIN', 'PAGE_DESCRIPTION', 'STRING', 'Я зарегистрирован на lova.su. Там вся страна!'),
('ua', 'MAIN', 'PAGE_TITLE', 'STRING', 'LOVA'),
('ua', 'MAIN', 'FORGOT_PASSWORD_LINK', 'STRING', 'Забыли пароль?'),
('ua', 'MAIN', 'LOGIN_EMAIL', 'STRING', 'Введите адрес почтового ящика'),
('ua', 'MAIN', 'LOGIN_EMAIL_HINT', 'STRING', 'E-mail'),
('ua', 'MAIN', 'LOGIN_PASSWORD', 'STRING', 'и пароль'),
('ua', 'MAIN', 'LOGIN_PASSWORD_HINT', 'STRING', 'Пароль'),
('ua', 'MAIN', 'LOGIN', 'STRING', 'Войти'),
('ua', 'MAIN', 'REGISTER', 'STRING', 'Регистрация'),
('ua', 'MAIN', 'SHARE_FACEBOOK', 'STRING', 'Поделиться в Facebook'),
('ua', 'MAIN', 'SHARE_VK', 'STRING', 'Поделиться В Контакте'),
('ua', 'MAIN', 'SHARE_ODNOKLASSNIKI', 'STRING', 'Добавить в Одноклассники'),
('ua', 'MAIN', 'SHARE_MAILRU', 'STRING', 'Поделиться в Моем Мире @Mail.ru'),
('ua', 'MAIN', 'REGISTER_WINDOW_CAPTION', 'STRING', 'Регистрация'),
('ua', 'MAIN', 'REGISTER_WINDOW_FIRST_NAME', 'STRING', 'Имя'),
('ua', 'MAIN', 'REGISTER_WINDOW_LAST_NAME', 'STRING', 'Фамилия'),
('ua', 'MAIN', 'REGISTER_WINDOW_LOGIN', 'STRING', 'Ник'),
('ua', 'MAIN', 'REGISTER_WINDOW_PASSWORD', 'STRING', 'Пароль'),
('ua', 'MAIN', 'REGISTER_WINDOW_EMAIL', 'STRING', 'Почта'),
('ua', 'MAIN', 'REGISTER_WINDOW_CLOSE_BTN', 'STRING', 'Закрыть'),
('ua', 'MAIN', 'REGISTER_WINDOW_REGISTER_BTN', 'STRING', 'Регистрация'),
('ua', 'MAIN', 'RESTORE_WINDOW_CAPTION', 'STRING', 'Восстановление пароля'),
('ua', 'MAIN', 'RESTORE_WINDOW_USER_NOT_FOUND', 'STRING', 'Ник или E-mail не найден'),
('ua', 'MAIN', 'RESTORE_WINDOW_EMAIL_WAS_SENT', 'STRING', 'Сcылка для восстановления пароля отправлена на почту'),
('ua', 'MAIN', 'RESTORE_WINDOW_LOGIN', 'STRING', 'Введите ник'),
('ua', 'MAIN', 'RESTORE_WINDOW_EMAIL', 'STRING', 'Или e-mail'),
('ua', 'MAIN', 'RESTORE_WINDOW_CLOSE_BTN', 'STRING', 'Закрыть'),
('ua', 'MAIN', 'RESTORE_WINDOW_RESTORE_BTN', 'STRING', 'Восстановить'),
('ua', 'PROFILE', 'PAGE_TITLE', 'STRING', 'LOVA - cabinet'),
('ua', 'PROFILE', 'PROFILE_FIELDS', 'STRING', 'Пожалуйста, заполните обязательные поля.'),
('ua', 'PROFILE', 'PROFILE_LANG_RU', 'STRING', 'Русский'),
('ua', 'PROFILE', 'PROFILE_LANG_EN', 'STRING', 'English'),
('ua', 'PROFILE', 'PROFILE_LANG_UA', 'STRING', 'Українська'),
('ua', 'PROFILE', 'PROFILE_LANG', 'STRING', 'Язык'),
('ua', 'PROFILE', 'PROFILE_FIRST_NAME', 'STRING', 'Имя'),
('ua', 'PROFILE', 'PROFILE_LAST_NAME', 'STRING', 'Фамилия'),
('ua', 'PROFILE', 'PROFILE_LOGIN', 'STRING', 'Ник'),
('ua', 'PROFILE', 'PROFILE_EMAIL', 'STRING', 'Почта'),
('ua', 'PROFILE', 'PROFILE_PASSWORD', 'STRING', 'Пароль'),
('ua', 'PROFILE', 'PROFILE_PHONE', 'STRING', 'Телефон'),
('ua', 'PROFILE', 'PROFILE_COUNTRY', 'STRING', 'Страна'),
('ua', 'PROFILE', 'PROFILE_SKYPE', 'STRING', 'Скайп'),
('ua', 'PROFILE', 'PROFILE_REFERAL', 'STRING', 'Пригласил'),
('ua', 'PROFILE', 'PROFILE_REFERAL_HINT', 'STRING', 'поле можно изменить в течении 7 дней с момента регистрации'),
('ua', 'PROFILE', 'PROFILE_SUBSCRIBE', 'STRING', 'Получать еженедельную рассылку'),
('ua', 'PROFILE', 'PROFILE_SAVE_BTN', 'STRING', 'Сохранить'),
('ua', 'PROFILE', 'PROFILE_CLOSE_BTN', 'STRING', 'Закрыть');

